services:
    postgres:
        image: postgres:16
        container_name: shareapp_postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    # minio:
    #     image: minio/minio:latest
    #     container_name: shareapp_minio
    #     command: server /data --console-address ":9001"
    #     environment:
    #         MINIO_ROOT_USER: ${MINIO_ROOT_USER}
    #         MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    #     ports:
    #         - "9000:9000"
    #         - "9001:9001"
    #     volumes:
    #         - minio_data:/data
    #     env_file:
    #         - .env
    garage:
        container_name: shareapp_garage
        image: dxflrs/garage:v2.1.0
        ports:
            - 3900:3900
            - 3901:3901
            - 3902:3902
        volumes:
            - ./garage.toml:/etc/garage.toml
            - garage-meta:/var/lib/garage/meta:rw
            - garage-data:/var/lib/garage/data:rw

volumes:
    postgres_data:
    # minio_data:
    garage-meta:
    garage-data: